### ISSUE TITLE
MinOZW segfaults when doing a clean build/run of the Dev branch

### ISSUE THREAD

**Issue by dhylands** [OpenZWave/open-zwave#1921]
It I do a new checkout of the open-zwave repository, checkout the Dev branch and build (debug or release) and run MinOZW then I get a segfault.

I'm building/running with Ubuntu 19.04 and using an Aeotec Z-Stick 5.

Commands executed:
```
git clone https://github.com/OpenZWave/open-zwave.git
cd open-zwave
git checkout Dev
BUILD=debug make
./MinOZW gdb
```

Here's the output on the console:
```
2141 >./MinOZW gdb
GNU gdb (Ubuntu 8.2.91.20190405-0ubuntu3) 8.2.91.20190405-git
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from .lib/MinOZW...
(gdb) set args /dev/ttyACM0
(gdb) run
Starting program: /home/dhylands/xxx/open-zwave/.lib/MinOZW /dev/ttyACM0
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Starting MinOZW with OpenZWave Version 1.6-840-g95a8c3c5-dirty
2019-08-30 16:28:55.628 Error, Cannot find a path to the configuration files at ../../../config/, Using config/ instead...
2019-08-30 16:28:55.628 Info, Reading config/options.xml for Options
2019-08-30 16:28:55.628 Warning, Failed to Parse options.xml: Failed to open file
2019-08-30 16:28:55.628 Info, Options:
2019-08-30 16:28:55.628 Info, 	appendlogfile: false
2019-08-30 16:28:55.628 Info, 	associate: true
2019-08-30 16:28:55.628 Info, 	assumeawake: true
2019-08-30 16:28:55.628 Info, 	autoupdateconfigfile: true
2019-08-30 16:28:55.628 Info, 	configpath: config/
2019-08-30 16:28:55.628 Info, 	consoleoutput: true
2019-08-30 16:28:55.628 Info, 	customsecuredcc: 0x62,0x4c,0x63
2019-08-30 16:28:55.628 Info, 	drivermaxattempts: 5
2019-08-30 16:28:55.628 Info, 	dumptrigger: 4
2019-08-30 16:28:55.628 Info, 	dumptriggerlevel: 1
2019-08-30 16:28:55.628 Info, 	enablesis: true
2019-08-30 16:28:55.628 Info, 	enforcesecurereception: true
2019-08-30 16:28:55.628 Info, 	exclude: 
2019-08-30 16:28:55.628 Info, 	include: 
2019-08-30 16:28:55.628 Info, 	includeinstancelabel: true
2019-08-30 16:28:55.628 Info, 	interface: 
2019-08-30 16:28:55.628 Info, 	intervalbetweenpolls: true
2019-08-30 16:28:55.628 Info, 	language: 
2019-08-30 16:28:55.628 Info, 	logfilename: OZW_Log.txt
2019-08-30 16:28:55.628 Info, 	logging: true
2019-08-30 16:28:55.628 Info, 	networkkey: 
2019-08-30 16:28:55.628 Info, 	notifyondriverunload: false
2019-08-30 16:28:55.628 Info, 	notifytransactions: false
2019-08-30 16:28:55.628 Info, 	performreturnroutes: false
2019-08-30 16:28:55.629 Info, 	pollinterval: 500
2019-08-30 16:28:55.629 Info, 	queueloglevel: 9
2019-08-30 16:28:55.629 Info, 	refreshallusercodes: false
2019-08-30 16:28:55.629 Info, 	reloadafterupdate: AWAKE
2019-08-30 16:28:55.629 Info, 	retrytimeout: 10000
2019-08-30 16:28:55.629 Info, 	saveconfiguration: true
2019-08-30 16:28:55.629 Info, 	saveloglevel: 8
2019-08-30 16:28:55.629 Info, 	securitystrategy: SUPPORTED
2019-08-30 16:28:55.629 Info, 	suppressvaluerefresh: false
2019-08-30 16:28:55.629 Info, 	userpath: 
2019-08-30 16:28:55.629 Info, 	validatevaluechanges: true
2019-08-30 16:28:55.629 Always, OpenZwave Version 1.6-840-g95a8c3c5-dirty Starting Up
2019-08-30 16:28:55.635 Info, Loading Localization File config/Localization.xml
2019-08-30 16:28:55.638 Info, Loaded config/Localization.xml With Revision 8
2019-08-30 16:28:55.639 Always, Using Language Localization 
2019-08-30 16:28:55.641 Info, Loading NotificationCCTypes File config/NotificationCCTypes.xml
2019-08-30 16:28:55.642 Info, Loaded config/NotificationCCTypes.xml With Revision 9
2019-08-30 16:28:55.643 Info, Loading SensorMultiLevelCCTypes File config/SensorMultiLevelCCTypes.xml
2019-08-30 16:28:55.643 Info, Loaded config/SensorMultiLevelCCTypes.xml With Revision 3
2019-08-30 16:28:55.644 Info, Setting Up Provided Network Key for Secure Communications
2019-08-30 16:28:55.644 Warning, Failed - Network Key Not Set
2019-08-30 16:28:55.654 Info, Manufacturer_Specific.xml file Revision is 38
2019-08-30 16:28:55.874 Info, Product name collision: FGR223 Roller Shutter Controller 3 type 303 id 1000 manufacturerid 10f, collides with FGRM223 Roller Shutter Controller 3, type 303 id 1000 manufacturerid 10f
2019-08-30 16:28:56.007 Info, Product name collision: ED2.0 Meter Adapter type 0 id 0 manufacturerid 128, collides with ED2.0 Meter Adapter, type 0 id 0 manufacturerid 128
2019-08-30 16:28:56.007 Info, Product name collision: ED2.0 Display type 128 id 0 manufacturerid 128, collides with ED2.0 Display, type 128 id 0 manufacturerid 128
2019-08-30 16:28:56.075 Info, Product name collision: GR105 Auto Valve type 202 id 511 manufacturerid 152, collides with GR105 Auto Valve, type 202 id 511 manufacturerid 152
2019-08-30 16:28:56.075 Info, Product name collision: GR105n Auto Valve type 3 id 512 manufacturerid 152, collides with GR105n Auto Valve, type 3 id 512 manufacturerid 152
2019-08-30 16:28:56.075 Info, Product name collision: ZSE02 Motion Sensor type 500 id 3 manufacturerid 152, collides with ZSE02 Motion Sensor, type 500 id 3 manufacturerid 152
2019-08-30 16:28:56.085 Info, Product name collision: ZWN-BPC Ceiling Mounted PIR Motion Sensor type 601 id 901 manufacturerid 11a, collides with ZWN-BPC Ceiling Mounted PIR Motion Sensor, type 601 id 901 manufacturerid 11a
2019-08-30 16:28:56.085 Info, Product name collision: ZWN-SC7 7-Button Scene Controller type 801 id b03 manufacturerid 11a, collides with ZWN-SC7 7-Button Scene Controller, type 801 id b03 manufacturerid 11a
2019-08-30 16:28:56.085 Info, Product name collision: ZW15S 15A On/Off Switch type 101 id 102 manufacturerid 11a, collides with ZW15S 15A On/Off Switch, type 101 id 102 manufacturerid 11a
2019-08-30 16:28:56.085 Info, Product name collision: ZW20R 20A TR Duplex Receptacle type 101 id 603 manufacturerid 11a, collides with ZW20R 20A TR Duplex Receptacle, type 101 id 603 manufacturerid 11a
2019-08-30 16:28:56.085 Info, Product name collision: ZWN-RSM1 PLUS-Smart Single Relay Switch Module type 111 id 605 manufacturerid 11a, collides with ZWN-RSM1 PLUS?Smart Single Relay Switch Module, type 111 id 605 manufacturerid 11a
2019-08-30 16:28:56.085 Info, Product name collision: ZW20RM 20A TR Smart Meter Duplex Receptacle type 111 id 101 manufacturerid 11a, collides with ZW20RM 20A TR Smart Meter Duplex Receptacle, type 111 id 101 manufacturerid 11a
2019-08-30 16:28:56.085 Info, Product name collision: ZW500D 500W In-Wall Preset Dimmer Switch type 102 id 201 manufacturerid 11a, collides with ZW500D 500W In-Wall Preset Dimmer Switch, type 102 id 201 manufacturerid 11a
2019-08-30 16:28:56.085 Info, Product name collision: ZW15RM Plus 15A TR Smart Meter Duplex Receptacle type 111 id 105 manufacturerid 11a, collides with ZW15RM Plus 15A TR Smart Meter Duplex Receptacle, type 111 id 105 manufacturerid 11a
2019-08-30 16:28:56.108 Info, Queuing Lookup on mfs.db.openzwave.com for Node 0
[New Thread 0x7ffff76a7700 (LWP 30774)]
2019-08-30 16:28:56.109 Info,   Opening controller /dev/ttyACM0
2019-08-30 16:28:56.109 Info, Trying to open serial port /dev/ttyACM0 (attempt 1)
[New Thread 0x7ffff6ea6700 (LWP 30775)]
2019-08-30 16:28:56.109 Info, Starting DNSThread
2019-08-30 16:28:56.109 Info, LookupTxT Checking mfs.db.openzwave.com
[New Thread 0x7ffff66a5700 (LWP 30776)]
2019-08-30 16:28:56.109 Info, Timer: thread starting
2019-08-30 16:28:56.110 Detail, Timer: waiting with timeout -1 ms
2019-08-30 16:28:56.110 Info, Lookup for mfs.db.openzwave.com returned 48
2019-08-30 16:28:56.110 Info, Serial port /dev/ttyACM0 opened (attempt 1)
2019-08-30 16:28:56.110 Info, mgr,     Added driver for controller /dev/ttyACM0
[New Thread 0x7ffff5ea4700 (LWP 30777)]
[New Thread 0x7ffff56a3700 (LWP 30778)]
2019-08-30 16:28:56.111 Detail, contrlr, Queuing (Command) FUNC_ID_ZW_GET_VERSION: 0x01, 0x03, 0x00, 0x15, 0xe9
2019-08-30 16:28:56.111 Detail, contrlr, Queuing (Command) FUNC_ID_ZW_MEMORY_GET_ID: 0x01, 0x03, 0x00, 0x20, 0xdc
2019-08-30 16:28:56.111 Detail, contrlr, Queuing (Command) FUNC_ID_ZW_GET_CONTROLLER_CAPABILITIES: 0x01, 0x03, 0x00, 0x05, 0xf9
2019-08-30 16:28:56.111 Detail, contrlr, Queuing (Command) FUNC_ID_SERIAL_API_GET_CAPABILITIES: 0x01, 0x03, 0x00, 0x07, 0xfb
2019-08-30 16:28:56.111 Detail, contrlr, Queuing (Command) FUNC_ID_ZW_GET_SUC_NODE_ID: 0x01, 0x03, 0x00, 0x56, 0xaa
2019-08-30 16:28:56.111 Warning, Config Revision of ManufacturerSpecific Database is out of date
2019-08-30 16:28:56.111 Info, Queuing download for http://download.db.openzwave.com/mfs.xml
[New Thread 0x7ffff4ea2700 (LWP 30779)]
2019-08-30 16:28:56.111 Detail, Notification: User Alert - Manufacturer_specific.xml out of Date
Notification: User Alert - Manufacturer_specific.xml out of Date
2019-08-30 16:28:56.481 Info, Download Finished: config/manufacturer_specific.xml (Node: 0)

Thread 2 "OZW-driver" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff76a7700 (LWP 30774)]
0x00007ffff00008d0 in ?? ()
(gdb)
```
Here's the gdb backtrace from the debug build.
```
(gdb) bt
#0  0x00007ffff00008d0 in ?? ()
#1  0x00007ffff7f13cca in std::_Sp_counted_ptr<OpenZWave::Internal::ProductDescriptor*, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x5555557afa70)
    at /usr/include/c++/8/bits/shared_ptr_base.h:377
#2  0x00007ffff7e298e6 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x5555557afa70) at /usr/include/c++/8/bits/shared_ptr_base.h:155
#3  0x00007ffff7e297db in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x5555557d2330, __in_chrg=<optimized out>)
    at /usr/include/c++/8/bits/shared_ptr_base.h:728
#4  0x00007ffff7e29732 in std::__shared_ptr<OpenZWave::Internal::ProductDescriptor, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x5555557d2328, __in_chrg=<optimized out>)
    at /usr/include/c++/8/bits/shared_ptr_base.h:1167
#5  0x00007ffff7e2974e in std::shared_ptr<OpenZWave::Internal::ProductDescriptor>::~shared_ptr (this=0x5555557d2328, __in_chrg=<optimized out>)
    at /usr/include/c++/8/bits/shared_ptr.h:103
#6  0x00007ffff7f137ca in std::pair<long long const, std::shared_ptr<OpenZWave::Internal::ProductDescriptor> >::~pair (this=0x5555557d2320, __in_chrg=<optimized out>)
    at /usr/include/c++/8/bits/stl_pair.h:208
#7  0x00007ffff7f137ea in __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<long long const, std::shared_ptr<OpenZWave::Internal::ProductDescriptor> > > >::destroy<std::pair<long long const, std::shared_ptr<OpenZWave::Internal::ProductDescriptor> > > (this=0x7ffff7fcbe60 <OpenZWave::Internal::ManufacturerSpecificDB::s_productMap>, __p=0x5555557d2320)
    at /usr/include/c++/8/ext/new_allocator.h:140
#8  0x00007ffff7f13565 in std::allocator_traits<std::allocator<std::_Rb_tree_node<std::pair<long long const, std::shared_ptr<OpenZWave::Internal::ProductDescriptor> > > > >::destroy<std::pair<long long const, std::shared_ptr<OpenZWave::Internal::ProductDescriptor> > > (__a=..., __p=0x5555557d2320) at /usr/include/c++/8/bits/alloc_traits.h:487
#9  0x00007ffff7f12b57 in std::_Rb_tree<long long, std::pair<long long const, std::shared_ptr<OpenZWave::Internal::ProductDescriptor> >, std::_Select1st<std::pair<long long const, std::shared_ptr<OpenZWave::Internal::ProductDescriptor> > >, std::less<long long>, std::allocator<std::pair<long long const, std::shared_ptr<OpenZWave::Internal::ProductDescriptor> > > >::_M_destroy_node (this=0x7ffff7fcbe60 <OpenZWave::Internal::ManufacturerSpecificDB::s_productMap>, __p=0x5555557d2300) at /usr/include/c++/8/bits/stl_tree.h:661
#10 0x00007ffff7f11a93 in std::_Rb_tree<long long, std::pair<long long const, std::shared_ptr<OpenZWave::Internal::ProductDescriptor> >, std::_Select1st<std::pair<long long const, std::shared_ptr<OpenZWave::Internal::ProductDescriptor> > >, std::less<long long>, std::allocator<std::pair<long long const, std::shared_ptr<OpenZWave::Internal::ProductDescriptor> > > >::_M_drop_node (this=0x7ffff7fcbe60 <OpenZWave::Internal::ManufacturerSpecificDB::s_productMap>, __p=0x5555557d2300) at /usr/include/c++/8/bits/stl_tree.h:669
#11 0x00007ffff7f12754 in std::_Rb_tree<long long, std::pair<long long const, std::shared_ptr<OpenZWave::Internal::ProductDescriptor> >, std::_Select1st<std::pair<long long const, std::shared_ptr<OpenZWave::Internal::ProductDescriptor> > >, std::less<long long>, std::allocator<std::pair<long long const, std::shared_ptr<OpenZWave::Internal::ProductDescriptor> > > >::_M_erase_aux (this=0x7ffff7fcbe60 <OpenZWave::Internal::ManufacturerSpecificDB::s_productMap>, Python Exception <class 'gdb.error'> No type named std::_Rb_tree_node<struct std::pair<long long const, std::shared_ptr<OpenZWave::Internal::ProductDescriptor> >>.: 
__position=...) at /usr/include/c++/8/bits/stl_tree.h:2493
#12 0x00007ffff7f11529 in std::_Rb_tree<long long, std::pair<long long const, std::shared_ptr<OpenZWave::Internal::ProductDescriptor> >, std::_Select1st<std::pair<long long const, std::shared_ptr<OpenZWave::Internal::ProductDescriptor> > >, std::less<long long>, std::allocator<std::pair<long long const, std::shared_ptr<OpenZWave::Internal::ProductDescriptor> > > >::erase[abi:cxx11](std::_Rb_tree_iterator<std::pair<long long const, std::shared_ptr<OpenZWave::Internal::ProductDescriptor> > >) (
    this=0x7ffff7fcbe60 <OpenZWave::Internal::ManufacturerSpecificDB::s_productMap>, Python Exception <class 'gdb.error'> No type named std::_Rb_tree_node<struct std::pair<long long const, std::shared_ptr<OpenZWave::Internal::ProductDescriptor> >>.: 
__position=...) at /usr/include/c++/8/bits/stl_tree.h:1141
#13 0x00007ffff7f10af5 in std::map<long long, std::shared_ptr<OpenZWave::Internal::ProductDescriptor>, std::less<long long>, std::allocator<std::pair<long long const, std::shared_ptr<OpenZWave::Internal::ProductDescriptor> > > >::erase[abi:cxx11](std::_Rb_tree_iterator<std::pair<long long const, std::shared_ptr<OpenZWave::Internal::ProductDescriptor> > >) (
    this=0x7ffff7fcbe60 <OpenZWave::Internal::ManufacturerSpecificDB::s_productMap>, Python Exception <class 'gdb.error'> No type named std::_Rb_tree_node<struct std::pair<long long const, std::shared_ptr<OpenZWave::Internal::ProductDescriptor> >>.: 
__position=...) at /usr/include/c++/8/bits/stl_map.h:1037
#14 0x00007ffff7f0f143 in OpenZWave::Internal::ManufacturerSpecificDB::UnloadProductXML (this=0x555555579160) at /home/dhylands/xxx/open-zwave/cpp/src/ManufacturerSpecificDB.cpp:276
#15 0x00007ffff7f0f9e8 in OpenZWave::Internal::ManufacturerSpecificDB::mfsConfigDownloaded (this=0x555555579160, driver=0x55555559ba90, file="config/manufacturer_specific.xml", 
    success=true) at /home/dhylands/xxx/open-zwave/cpp/src/ManufacturerSpecificDB.cpp:368
#16 0x00007ffff7f09630 in OpenZWave::Driver::processDownload (this=0x55555559ba90, download=0x7ffff0001ea0) at /home/dhylands/xxx/open-zwave/cpp/src/Driver.cpp:6990
#17 0x00007ffff7f09c83 in OpenZWave::Driver::ProcessEventMsg (this=0x55555559ba90) at /home/dhylands/xxx/open-zwave/cpp/src/Driver.cpp:7082
#18 0x00007ffff7ef26f2 in OpenZWave::Driver::DriverThreadProc (this=0x55555559ba90, _exitEvent=0x55555557b730) at /home/dhylands/xxx/open-zwave/cpp/src/Driver.cpp:426
#19 0x00007ffff7ef22ba in OpenZWave::Driver::DriverThreadEntryPoint (_exitEvent=0x55555557b730, _context=0x55555559ba90) at /home/dhylands/xxx/open-zwave/cpp/src/Driver.cpp:322
#20 0x00007ffff7e8d908 in OpenZWave::Internal::Platform::ThreadImpl::Run (this=0x555555578910) at /home/dhylands/xxx/open-zwave/cpp/src/platform/unix/ThreadImpl.cpp:166
#21 0x00007ffff7e8d8cc in OpenZWave::Internal::Platform::ThreadImpl::ThreadProc (_pArg=0x555555578910) at /home/dhylands/xxx/open-zwave/cpp/src/platform/unix/ThreadImpl.cpp:153
#22 0x00007ffff7a0a182 in start_thread (arg=<optimized out>) at pthread_create.c:486
#23 0x00007ffff7933b1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) 
```

The master branch doesn't segfault when doing the same steps.

Running `./MinOZW /dev/ttyACM0` a second time works fine, so it the crash appears to be related to downloading config files.

**Comment by Fishwaldo** [comment]
I just pushed a fix here. As usual, strange it doesn't crash on Master as it has the same bug. Thanks for the detailed report - Appreciated.

**Comment by dhylands** [comment]
I suspect that it didn't crash on master because it didn't need to download any updated configs.
