### ISSUE TITLE
Segfault with Aeotec Home Energy Meter

### ISSUE THREAD

**Issue by Zkral** [OpenZWave/open-zwave#1957]
Hi,

I'm using the Dev branch, and since I updated to the latest commit (c26f487ce3e7893287f5a143e51e3bdf2943fdb5), I'm having a segfault when my Aeotec Home Energy Meter (manufacturer=0x0086, type=0x0002, id=0x005f, file aeotec/zw095.xml) sends an update. It worked fine before, with commit 22704d906fcf69e26ef46d3ba45492620d96af6f.

This is the last log messages for this node before the segfault:

2019-09-30 09:21:55.049 Info, Node021, Received CRC16-command from node 21
2019-09-30 09:21:55.050 Info, Node021, Received Meter Report for Electric - W (1) with Units W (2) on Index 2: 307.532

Please find gdb backtrace below. I dont have time to investigate this further at the moment, so I'm posting this in case anyone has an idea.

Thanks.

```
(gdb) bt
#0  0x00007ffff64f70ba in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff6da5a73 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007ffff6da5d99 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff7466230 in OpenZWave::Internal::VC::ValueDecimal::OnValueRefreshed (this=0x7fffec4367f0, _value="307.532") at cpp/src/value_classes/ValueDecimal.cpp:113
#4  0x00007ffff73e2872 in OpenZWave::Internal::CC::Meter::HandleReport (this=0x7fffec434bf0, _data=0x7ffff473a8ba "\002!t", _length=14, _instance=1) at cpp/src/command_classes/Meter.cpp:389
#5  0x00007ffff73e1d49 in OpenZWave::Internal::CC::Meter::HandleMsg (this=0x7fffec434bf0, _data=0x7ffff473a8ba "\002!t", _length=14, _instance=1) at cpp/src/command_classes/Meter.cpp:278
#6  0x00007ffff7406e32 in OpenZWave::Internal::CC::CRC16Encap::HandleMsg (this=0x7fffec43b120, _data=0x7ffff473a8b8 "\001\062\002!t", _length=18, _instance=1) at cpp/src/command_classes/CRC16Encap.cpp:94
#7  0x00007ffff74b2944 in OpenZWave::Node::ApplicationCommandHandler (this=0x7fffec42ffe0, _data=0x7ffff473a8b2 "", encrypted=true) at cpp/src/Node.cpp:1959
#8  0x00007ffff750249a in OpenZWave::Driver::HandleApplicationCommandHandlerRequest (this=0x5555557ba0a0, _data=0x7ffff473a8b2 "", encrypted=true) at cpp/src/Driver.cpp:3598
#9  0x00007ffff74fd904 in OpenZWave::Driver::ProcessMsg (this=0x5555557ba0a0, _data=0x7ffff473a8b2 "", _length=44 ',') at cpp/src/Driver.cpp:2170
#10 0x00007ffff74fc3c7 in OpenZWave::Driver::ReadMsg (this=0x5555557ba0a0) at cpp/src/Driver.cpp:1684
#11 0x00007ffff74f7f5b in OpenZWave::Driver::DriverThreadProc (this=0x5555557ba0a0, _exitEvent=0x555555798330) at cpp/src/Driver.cpp:438
#12 0x00007ffff74f7ae8 in OpenZWave::Driver::DriverThreadEntryPoint (_exitEvent=0x555555798330, _context=0x5555557ba0a0) at cpp/src/Driver.cpp:322
#13 0x00007ffff74776fc in OpenZWave::Internal::Platform::ThreadImpl::Run (this=0x555555799940) at cpp/src/platform/unix/ThreadImpl.cpp:166
#14 0x00007ffff74776c0 in OpenZWave::Internal::Platform::ThreadImpl::ThreadProc (_pArg=0x555555799940) at cpp/src/platform/unix/ThreadImpl.cpp:153
#15 0x00007ffff7bc34a4 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#16 0x00007ffff64b6d0f in clone () from /lib/x86_64-linux-gnu/libc.so.6
```

```
(gdb) bt full
#0  0x00007ffff64f70ba in ?? () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x00007ffff6da5a73 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#2  0x00007ffff6da5d99 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#3  0x00007ffff7466230 in OpenZWave::Internal::VC::ValueDecimal::OnValueRefreshed (this=0x7fffec4367f0, _value="307.532") at cpp/src/value_classes/ValueDecimal.cpp:113
No locals.
#4  0x00007ffff73e2872 in OpenZWave::Internal::CC::Meter::HandleReport (this=0x7fffec434bf0, _data=0x7ffff473a8ba "\002!t", _length=14, _instance=1) at cpp/src/command_classes/Meter.cpp:389
        scale = 2 '\002'
        precision = 3 '\003'
        valueStr = "307.532"
        meterType = 1 '\001'
        index = 2
        value = 0x7fffec4367f0
        exporting = false
#5  0x00007ffff73e1d49 in OpenZWave::Internal::CC::Meter::HandleMsg (this=0x7fffec434bf0, _data=0x7ffff473a8ba "\002!t", _length=14, _instance=1) at cpp/src/command_classes/Meter.cpp:278
        handled = false
#6  0x00007ffff7406e32 in OpenZWave::Internal::CC::CRC16Encap::HandleMsg (this=0x7fffec43b120, _data=0x7ffff473a8b8 "\001\062\002!t", _length=18, _instance=1) at cpp/src/command_classes/CRC16Encap.cpp:94
        pCommandClass = 0x7fffec434bf0
        commandClassId = 50 '2'
        node = 0x7fffec42ffe0
        crcM = 42049
        crcC = 42049
#7  0x00007ffff74b2944 in OpenZWave::Node::ApplicationCommandHandler (this=0x7fffec42ffe0, _data=0x7ffff473a8b2 "", encrypted=true) at cpp/src/Node.cpp:1959
        pCommandClass = 0x7fffec43b120
#8  0x00007ffff750249a in OpenZWave::Driver::HandleApplicationCommandHandlerRequest (this=0x5555557ba0a0, _data=0x7ffff473a8b2 "", encrypted=true) at cpp/src/Driver.cpp:3598
        status = 0 '\000'
        nodeId = 21 '\025'
        classId = 86 'V'
        node = 0x7fffec42ffe0
#9  0x00007ffff74fd904 in OpenZWave::Driver::ProcessMsg (this=0x5555557ba0a0, _data=0x7ffff473a8b2 "", _length=44 ',') at cpp/src/Driver.cpp:2170
        handleCallback = true
        wasencrypted = true
#10 0x00007ffff74fc3c7 in OpenZWave::Driver::ReadMsg (this=0x5555557ba0a0) at cpp/src/Driver.cpp:1684
        ack = 6 '\006'
        length = 46
        str = "0x01, 0x2c, 0x00, 0x04, 0x00, 0x15, 0x26, 0x98, 0x81, 0xe5, 0xda, 0x80, 0x91, 0x71, 0xa4, 0x97, 0xf4, 0x20, 0x58, 0xe9, 0xf4, 0xb7, 0x19, 0x94, 0xdb, 0xda, 0xad, 0x8f, 0x1f, 0x11, 0xc4, 0x9b, 0xfd, 0x"...
        response = 0
        nodeId = 21 '\025'
        checksum = 166 '\246'
        buffer = "\001,\000\004\000\025\022V\001\062\002!t\000\004\261L\000\v\000\004\261\237\244Aڭ\217\037\021ě\375I-\301\327j8~\022\337i]\264\246", '\000' <repeats 977 times>
#11 0x00007ffff74f7f5b in OpenZWave::Driver::DriverThreadProc (this=0x5555557ba0a0, _exitEvent=0x555555798330) at cpp/src/Driver.cpp:438
        count = 4
        timeout = 9106
        res = 3
        waitObjects = {0x555555798330, 0x5555558817d0, 0x5555558818d0, 0x5555558810f0, 0x555555881aa0, 0x555555881ba0, 0x5555557dc150, 0x555555797bf0, 0x555555797cf0, 0x555555797df0, 0x555555797ef0}
        retryTimeStamp = {m_pImpl = 0x7fffec000b50}
        retryTimeout = 10000
        maxAttempts = 0
        attempts = 0
        mfsisReady = true
#12 0x00007ffff74f7ae8 in OpenZWave::Driver::DriverThreadEntryPoint (_exitEvent=0x555555798330, _context=0x5555557ba0a0) at cpp/src/Driver.cpp:322
        driver = 0x5555557ba0a0
#13 0x00007ffff74776fc in OpenZWave::Internal::Platform::ThreadImpl::Run (this=0x555555799940) at cpp/src/platform/unix/ThreadImpl.cpp:166
No locals.
#14 0x00007ffff74776c0 in OpenZWave::Internal::Platform::ThreadImpl::ThreadProc (_pArg=0x555555799940) at cpp/src/platform/unix/ThreadImpl.cpp:153
        pImpl = 0x555555799940
#15 0x00007ffff7bc34a4 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
No symbol table info available.
#16 0x00007ffff64b6d0f in clone () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
```

**Comment by Fishwaldo** [comment]
The Dev Branch is WIP to fix another issue. Please use master at the moment.
