### ISSUE TITLE
Always get a segfault after delete zwcfg!!!!

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OpenZWave/open-zwave#400]
```
Hi,

I had my network running fine until I decided to delete my zwcfg after the last 
update.

It turns out that my application never worked again, everytime the network is 
starting I get a segmentation fault and it dies...

Here goes the gdb stacktrace:

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xb7090b70 (LWP 9685)]
0xb74a4cf8 in 
std::__detail::_List_node_base::_M_hook(std::__detail::_List_node_base*) () 
from /usr/lib/i386-linux-gnu/libstdc++.so.6
(gdb) backtrace
#0  0xb74a4cf8 in 
std::__detail::_List_node_base::_M_hook(std::__detail::_List_node_base*) () 
from /usr/lib/i386-linux-gnu/libstdc++.so.6
#1  0xb7646468 in 
OpenZWave::Driver::QueueNotification(OpenZWave::Notification*) ()
#2  0xb7615d10 in OpenZWave::ManufacturerSpecific::HandleMsg(unsigned char 
const*, unsigned int, unsigned int) ()
#3  0xb75ef8ed in OpenZWave::Node::ApplicationCommandHandler(unsigned char 
const*) ()
#4  0xb76434e2 in 
OpenZWave::Driver::HandleApplicationCommandHandlerRequest(unsigned char*) ()
#5  0xb764e613 in OpenZWave::Driver::ProcessMsg(unsigned char*) ()
#6  0xb764f58a in OpenZWave::Driver::ReadMsg() ()
#7  0xb764f94b in OpenZWave::Driver::DriverThreadProc(OpenZWave::Event*) ()
#8  0xb764fb47 in OpenZWave::Driver::DriverThreadEntryPoint(OpenZWave::Event*, 
void*) ()
#9  0xb76602be in OpenZWave::ThreadImpl::Run() () 
#10 0xb76602fb in OpenZWave::ThreadImpl::ThreadProc(void*) ()
#11 0xb7fb4c39 in start_thread () from 
/lib/i386-linux-gnu/i686/cmov/libpthread.so.0
#12 0xb7ed978e in clone () from /lib/i386-linux-gnu/i686/cmov/libc.so.6

I have polycontrol doorlock and keypad secured devices, one ehk switch and 1 
aeon labs multi sensor...


```

Original issue reported on code.google.com by `santal.m...@gmail.com` on 20 Nov 2014 at 11:48

**Comment by killercode** [comment]
Greetings,

I found that the issue is with the EHK switchkeeper!

When I create a configuration file to avoid using command classes that where causing the network to hang when doing several attempts to send a command class, somehow there are some messages that are missinterpreted by the openzwave

All I saw it that the device sends a proprietary report and then openzwave says that it's a invalid HomeID (and the homeId presented is completly wrong). Could it be bad parsing of a proprietary message?

Does someone know to properly configure this device?
